// <auto-generated />
using System;
using CryptoApi.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(CryptoApiDbContext))]
    partial class CryptoApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            
            modelBuilder.Entity("CryptoApi.Models.Network", b =>
                {
                    b.Property<int>("Networkid")
                        .HasColumnType("int");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Networkid");

                    b.ToTable("Network");
                });

            
            modelBuilder.Entity("CryptoApi.Models.SymbolCoin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Blockchain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Networkid")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Networkid");

                    b.ToTable("SymbolCoin");
                });

            modelBuilder.Entity("CryptoApi.Models.SymbolCoin", b =>
                {
                    b.HasOne("CryptoApi.Models.Network", "Network")
                        .WithMany()
                        .HasForeignKey("Networkid");

                    b.Navigation("Network");
                });
#pragma warning restore 612, 618
        }
    }
}
